export const SET_SINGER = 'SET_SINGER'
export const SHOW_CONTENT = 'SHOW_CONTENT'

export const SET_PLAYING = 'SET_PLAYING'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAY_LIST = 'SET_PLAY_LIST'

export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

export const SET_MODE = 'SET_MODE'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_DISC = 'SET_DISC'

export const SET_TOPLIST = "SET_TOPLIST"

export const SET_SHOWSEARCH = "SET_SHOWSEARCH"

export const SET_SEARCHTEXT = "SET_SEARCHTEXT"

export const SET_SEARCHRESULT = 'SET_SEARCHRESULT'

export const SET_PERPAGE = 'SET_PERPAGE'

export const SET_P = 'SET_P'

export const SET_HASMORE = 'SET_HASMORE'

export const SET_LISTSCROLL = 'SET_LISTSCROLL'

export const SET_SEARCHHISTORY = 'SET_SEARCHHISTORY'

export const SET_SHOWCONFIRM = 'SET_SHOWCONFIRM'

export const SET_SHOWPARAM = 'SET_SHOWPARAM'

export const SET_PLAYHISTORY = 'SET_PLAYHISTORY'

export const SET_SEARCHMODE = 'SET_SEARCHMODE'

export const SET_FAVORITELIST = 'SET_FAVORITELIST'